name: Create Website Release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build website
      run: npm run website

    - name: Compress dist package
      run: |
        mkdir -p dist
        cd build/website/routes
        tar -czf ../../../dist/website.tar.gz *
        zip -r ../../../dist/website.zip .
        cd ../../..

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "website.tar.gz,website.zip"
